<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <OutputType>WinExe</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWPF>true</UseWPF>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <OutputPath>..\00_client_bin\</OutputPath>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MessagePack">
      <Version>2.5.129</Version>
    </PackageReference>
    <PackageReference Include="Z.ExtensionMethods">
      <Version>2.1.1</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.Windows.Compatibility" Version="10.0.0" />
  </ItemGroup>
</Project>
